apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-backend
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.backend.config }}
  {{- if eq $value "" }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
