apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.fullname" . }}-flower
  labels:
    {{- include "core.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value :=  .Values.flower.secret }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
