name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: '3.x'

      - name: Package Helm Chart
        run: |
          helm package ./ --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.tgz'
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
